<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

<title>Listado de requerimientos - <?php echo $this->usuario->nombres . " " . $this->usuario->primerApellido . " " . $this->usuario->segundoApellido;?></title>

<style type="text/css">


@page {
	margin: 1.2cm;
}

body {
  	font-family: sans-serif;
	margin: 1.9cm 0 1.6cm 0;
	text-align: justify;
	font-size: 0.8em;
	color: #222;
}

#header,
#footer {
 	position: fixed;
  	left: 0;
	right: 0;
	color: #aaa;
	font-size: 1.0em;
}

#header {
  	top: 0;
	/*border-bottom: 0.1pt solid #aaa;*/
	margin-bottom: 50px;
}

#footer {
  bottom: 0;
  border-top: 0.1pt solid #aaa;
  font-size: 0.9em;
}

#header table,
#footer table {
	margin; 1pt;
	width: 100%;
	border-collapse: collapse;
	border: none;
	font-size: 0.9em;
}

#header td,
#footer td {
  	padding: 0;
	width: 50%;
}

.page-number {
  text-align: center;
}

.page-number:before {
  content: "Page " counter(page);
}

hr {
  page-break-after: always;
  border: 0;
}

#content{
    color: #3C3A3B;	
}

td{
	border-top: 1px solid #ddd;
	vertical-align: middle;
	line-height: 1.42857;
    padding: 8px;
}
</style>
  
</head>

<body>

<div id="header">
	<strong style="text-align: center">Listado de requerimientos<br></br></strong>
	Semestre: <strong><?php echo $this->semestre;?></strong> ||| 
	Escuela: <strong><?php echo $this->escuela->nombreEscuela;?></strong> ||| 
	Curso: <strong><?php echo $this->curso->nombreCurso;?></strong> ||| 
	Docente: <strong><?php echo $this->usuario->nombres . " " . $this->usuario->primerApellido . " " . $this->usuario->segundoApellido;?></strong>
<br/>
<br/>
</div>

<div id="footer">
  <div class="page-number"></div>
  <div><?php echo date("d-M-Y H:i:s")?></div>
</div>

<div id="content">
<?php if($this->pedidos != null): ?>
	<table class="table">
	    <thead>
	    <tr>
	        <th>N°</th>
	        <th>Semestre</th>
	        <th>Tipo</th>
	        <th>Elemento</th>
	        <th>Unidad de Medida</th>        
	        <th>Cantidad Total</th>
	        <th>Obervaciones</th>
	    </tr>
	    </thead>
	    <tbody>
	    <?php
	    	$i = 0;
	    	foreach ($this->pedidos as $pedido) :
			$i++;
		?>    
	    <tr>
	        <td><?php echo $i;?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['semestre']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['tipo']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['elemento']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['unidadMedida']);?></td>
	        
	        <td><strong><?php echo $this->escapeHtml($pedido['cantidad']);?></strong></td>
	        
	        <td><strong><?php echo $this->escapeHtml($pedido['detalleObservacion']);?></strong></td>		        		        
	        
	    </tr>
	    <?php endforeach; ?>
	    </tbody>
	</table>
	<?php else: ?>
	
		<h2>No se han encontrado resultados</h2>

	<?php endif;?>	
</div>
</body>
</html>
