<?php 
if (defined('RUNNING_FROM_ROOT')) {
    //$this->plugin('basePath')->setBasePath($this->basePath().'/public'); 
} ?>

<?php echo $this->doctype(); ?>


<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Cachuelapp')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon2.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/uikit.min.css'))
            ->prependStylesheet($this->basePath('css/uikit-rtl.min.css'))
        ?>
        
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/canvas.js'))
            ->prependFile($this->basePath('js/uikit-icons.min.js'))
            ->prependFile($this->basePath('js/uikit.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

    </head>
    <body>        
        <div class="uk-container">      
            <?php echo $this->content; ?>
        </div> 
    </body>
</html>

