<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('ingresar', array('controller' => 'index', 'action' => 'index')));
$form->prepare();
?>

<script src='https://www.google.com/recaptcha/api.js'></script>
<script>
   function onSubmit(token) {
     document.getElementById("loginForm").submit();
   }
 </script>
 
<div class="" uk-height-viewport="offset-bottom: 20">
    <div class="uk-container-center uk-text-center uk-padding-small" style="background-color: #00A79D">
    	<div class="uk-h1"><i uk-icon="icon: sign-in"></i>Ingresar</div>
    	
    	<?php echo $this->form()->openTag($form); ?>
    	
    	<?php
            if ($this->messages):
                foreach ($this->messages as $msg):
                    ?>
                    <div class="uk-label-success uk-padding-small uk-margin"> <?php echo $msg; ?></div>
                <?php
                endforeach;
            endif;
       	?>
    	<?php
            if ($this->errorMessages):
                foreach ($this->errorMessages as $msg):
                    ?>
                    <div class="uk-label-danger uk-padding-small uk-margin"><?php echo $msg; ?></div>
                <?php
                endforeach;
            endif;
       	?>
       	
       	<?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<div class="uk-label-danger uk-padding-small uk-margin">')
                    ->setMessageSeparatorString('</div><div class="uk-label-danger uk-padding-small uk-margin">')
                    ->setMessageCloseString('</div>')
                    ->render($form->get('ingresar'));?>
    	
        <div class="uk-margin">
        	
        	<?php echo $this->formHidden($form->get('csrf')) ?>
        	<?php echo $this->formElementErrors()
                        ->setMessageOpenFormat('<div class="uk-badge">')
                        ->setMessageSeparatorString('</div><div class="uk-badge">')
                        ->setMessageCloseString('</div>')
                        ->render($form->get('csrf'));?>                
        
            <div class="uk-margin">
            	<?php //echo $this->formLabel($form->get('usuario')) ?>
                <?php echo $this->formInput($form->get('usuario')); ?>
                <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<div class="uk-badge">')
                    ->setMessageSeparatorString('</div><div class="uk-badge">')
                    ->setMessageCloseString('</div>')
                    ->render($form->get('usuario'));?>
            </div>
            <div class="uk-margin">
               <?php //echo $this->formLabel($form->get('clave')) ?>
               <?php echo $this->formInput($form->get('clave')); ?>
               <?php echo $this->formElementErrors()
                        ->setMessageOpenFormat('<div class="uk-badge">')
                        ->setMessageSeparatorString('</div><div class="uk-badge">')
                        ->setMessageCloseString('</div>')
                        ->render($form->get('clave'));?>
            </div>           	
    
            <div class="box-footer">                                                               
                <?php echo $this->formInput($form->get('ingresar')); ?>
            </div>
    
        </div>
                    
    	<?php echo $this->form()->closeTag($form);?>
    </div>
    <footer class="uk-text-center">
    	<h2 style="color: #34313A">¿Problemas?</h2>
    	<p>Estamos para apoyarte<br/>
    	Envíanos un correo o llámanos</p>
    	<p>
    		<span class="uk-icon-button" uk-icon="icon: mail" ratio="2"></span><a href="mailto:informatica.biologia@unmsm.edu.pe" >informatica.biologia@unmsm.edu.pe</a>
    		<span class="uk-icon-button" uk-icon="icon: receiver" ratio="2"></span><a href="tel:6197000" >Tel: 619-7000 Anexo: 1536</a>
    	</p>
    	<span style="background-color: #D3E7FF">Palvel esta atento a sugerencias y comentarios para seguir mejorando</span>
    </footer>
</div>










