<?php // module/Application/view/empleos/index/listar-terrenos.phtml: ?>

<?php
$title = 'Listado de Pedidos' ;
$this->headTitle($title);
?>

<div class="uk-container uk-container-expand uk-padding-small">

<h2 class="uk-text-center"><?= $this->escapeHtml($title) ?></h2>

<p>Docente: <strong><?php echo $this->usuario->nombres . " " . $this->usuario->primerApellido . " " . $this->usuario->segundoApellido;?></strong></p>
<p>
Curso: <strong><?php echo $this->curso->nombreCurso;?></strong> - 
<a class="uk-button uk-button-default" 
		href="<?php echo $this->url("admin", [
								     'action' => 'listar-cursos',
                                     'codusuario' => $this->codUsuario
		                     ]); ?>">Seleccionar otro curso</a>
</p>


<hr/>

<?php
    if ($this->messages):
        foreach ($this->messages as $msg):
            ?>
            <div class="uk-label-success uk-padding-small uk-margin"><?php echo $msg; ?></div>
        <?php
        endforeach;
    endif;
?>
<?php
if ($this->errorMessages):
    foreach ($this->errorMessages as $msg):
        ?>
			<div class="uk-label-danger uk-padding-small uk-margin">                         
				<?php echo $msg; ?>
			</div>
		<?php
		endforeach;
	endif;
?>

<?php if ($this->requerimientos->count() != 0):?>

    <table class="uk-table uk-table-hover uk-table-divider uk-table-striped">
	    <thead>
	    <tr>
	        <th>N°</th>	
	        <th>Semestre</th>		        
	        <th>Tipo</th>
	        <th>Elemento</th>
	        <th>Unidad de medida</th>
	        <th>Cantidad</th>
	        <th>Observaciones</th>
	    </tr>
	    </thead>
	    <tbody>
	    <?php
	    	$i = 0;
	    	foreach ($this->requerimientos as $requerimiento) :
			$i++;
		?>    
	    <tr>
	        <td><?php echo $i;?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->semestre);?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->tipo);?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->elemento);?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->unidadMedida);?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->cantidad);?></td>
	        
	        <td><?php echo $this->escapeHtml($requerimiento->detalleObservacion);?></td>
	        
	    </tr>
	    <?php endforeach; ?>
	    </tbody>
	</table>
	
	<a href="<?php echo $this->url('reportes', 
	    ['action'  => 'segundo-reporte-pdf',
         'imprimirpdf' => 'si',
         'codusuario' => $this->codUsuario,
	     'semestre' => $this->semestre,
	     'codescuela' => $this->codEscuela,
	     'codcurso' => $this->curso->codCurso]
	    ); ?>" class="uk-button uk-button-default" target="_blank">Descargar Pdf</a>
    
    
<?php else:?>
	<p>¡No se han encontrado resultados!</p>
<?php endif;?>

</div>