<div class="uk-container uk-padding">

	<div class="ul-grid" uk-grid>

		<div class="uk-width-1-2">
    		<h3>Reportes</h3>
    
        	<p>Resumen General del Total de Terrenos</p>
        
        	<hr/>
			<table class="uk-table uk-table-striped">
				<thead>
				<tr>
					<th style="text-align: center;">Terrenos Totales</th>
					<th style="text-align: center;">Vendidos</th>
					<th style="text-align: center;">Por vender</th>
				</tr>
				</thead>
				<tbody>
					<tr>
						<td style="text-align: center;"><?=$this->totalTerrenos; ?></td>
			        	<td style="text-align: center;"><?=$this->totalVendidos; ?></td>
			        	<td style="text-align: center;"><?=$this->totalSinVender; ?></td>
			    	</tr>
			    </tbody>
			</table>
			
			<h3>Otros reportes:</h3>
			<hr/>
        	<div>
        		<p><a href="<?php echo $this->url('reportes', [
                        'controller' => 'reporte',
                        'action' => 'pagos'
                    ]); ?>" >Reporte de pagos</a></p>
        	</div>
		</div>
		<div class="uk-width-1-2">
			<canvas id="myChart" width="300" height="150"></canvas>
		</div>
	</div>	

	<script>
		var totalTerrenos = <?=$this->totalTerrenos; ?>;
		var totalVendidos = <?=$this->totalVendidos; ?>;
		var totalSinVender = <?=$this->totalSinVender; ?>;

		var ctx = document.getElementById("myChart");
		var myChart = new Chart(ctx, {
		    type: 'pie',
		    data: {
		        labels: ["Vendidos", "Sin Vender"],
		        datasets: [
		        {
		            label: 'Terrenos',
		            data: [totalVendidos, totalSinVender],
		            backgroundColor: ['rgba(0, 255, 0, 0.2)', 'rgba(255, 0, 0, 0.2)'],
		            borderColor: ['rgba(0, 255, 0, 1)', 'rgba(255, 0, 0, 1)'],
		            borderWidth: 1
		        }
		        ]
		    },
		    options: {
		    }
		});
	</script>
</div>	