
<?php 
$usuario = $this->usuario_helper($this->identity()['codUsuario'], $this->identity()['rol']);
//var_dump($usuario); //return ;
?>

<!-- DIV PRINCIPAL -->
<div class="uk-container uk-padding" >
<div class="col-md-12" >	
	<div class="box">
		<div class="box-title">
			<h3>Perfil de usuario</h3>
		</div>
		<?php
            if ($this->messages):
                foreach ($this->messages as $msg):
                    ?>
                    <div class="uk-label-success uk-padding-small uk-margin"> <?php echo $msg; ?></div>
                <?php
                endforeach;
            endif;
       	?>
    	<?php
            if ($this->errorMessages):
                foreach ($this->errorMessages as $msg):
                    ?>
                    <div class="uk-label-danger uk-padding-small uk-margin"><?php echo $msg; ?></div>
                <?php
                endforeach;
            endif;
       	?>
		<div class="box-body padding-md"> <!-- DIV BODY END -->
			<div class="uk-card uk-card-default uk-card-body">
			<div  uk-grid> <!-- IMAGEN + PERFIL -->
				<div class="uk-width-1-4@l">
					<?php 
						$subirImagenForm = $this->subirImagenForm;
						$subirImagenForm->setAttribute('action', $this->url('perfil', array('action' => 'subir-imagen')));
						$subirImagenForm->prepare();
					?>
					<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
					
						<div id="profile" class="uk-inline-clip uk-transition-toggle">
							<a href="javascript:void(0);">
								<div class="uk-cover-container uk-height-small">
									<canvas width="" height="220"></canvas>
									<img src="<?php echo $this->basepath('img/perfil/');?><?php echo ($usuario->imagenPerfil == null) ? 'default.png' :  $usuario->imagenPerfil; ?>" class="profile-image img-rounded img-responsive" id="profileImg" uk-cover/>
								</div>
								<div  class="uk-overlay uk-overlay-default uk-transition-slide-bottom uk-position-bottom">
                                    <strong id="uploadTrigger"><span uk-icon="icon: camera"></span>Cambiar</b></strong>
                                	<?php echo $this->form()->openTag($subirImagenForm);?>
                                	<div class="uk-form-custom uk-hidden">
        								<?php echo $this->formFile($subirImagenForm->get('imagen')); ?>
        								<button class="uk-button uk-button-default" type="button" tabindex="-1"></button>
    								</div>
    								<?php echo $this->form()->closeTag(); ?>
                                </div>
							</a>
						</div>
						<div style="top: 2px;"></div>
						<div id="mensaje"></div>
					
				</div>

				<div class="uk-width-3-4@l">
					<h3><?php echo ucfirst(strtoupper($usuario->nombres)) . ' ' . strtoupper($usuario->primerApellido) . ' ' . strtoupper($usuario->segundoApellido);?></h3>
					<p><?php echo strtoupper($usuario->rol);?></p>
					<p><?php echo $usuario->correo;?></p>
					<hr/>
					<a class="uk-button uk-button-primary" href="<?php echo $this->url('perfil' , array('action' => 'editar-perfil'));?>">Editar perfil</a>
				</div>
				
			</div><!-- IMAGEN + PERFIL END -->
			</div>

		</div><!-- DIV BODY END -->
	</div>
</div>
</div>
<!-- DIV PRINCIPAL -->
