<?php // module/Application/view/empleos/index/listar-pagos.phtml: ?>

<?php
$title = 'Listado general de requerimientos';
$this->headTitle($title);
?>
<div class="uk-container uk-container-expand uk-padding-small" >
<h2 class="uk-text-center"><?= $this->escapeHtml($title) ?></h2>

<a class="uk-button uk-button-secondary" href="<?php echo $this->url("admin", ['action' => 'listar-usuarios']); ?>" >Ver pedidos por docentes</a>

<?php
    if ($this->messages):
        foreach ($this->messages as $msg):
            ?>
            <div class="uk-label-success uk-padding-small uk-margin"><?php echo $msg; ?></div>
        <?php
        endforeach;
    endif;
?>
<?php
if ($this->errorMessages):
    foreach ($this->errorMessages as $msg):
        ?>
			<div class="uk-label-danger uk-padding-small uk-margin">                         
				<?php echo $msg; ?>
			</div>
		<?php
		endforeach;
	endif;
?>

<?php if($this->pedidos->count()!= 0):?>
	<table class="uk-table uk-table-divider uk-table-striped">
	    <thead>
	    <tr>
	        <th>N°</th>
	        <th>Semestre</th>
	        <th>Tipo</th>
	        <th>Elemento</th>
	        <th>Unidad de Medida</th>        
	        <th>Cantidad Total</th>
	    </tr>
	    </thead>
	    <tbody>
	    <?php
	    	$i = 0;
	    	foreach ($this->pedidos as $pedido) :
			$i++;
		?>    
	    <tr>
	        <td><?php echo $i;?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['semestre']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['tipo']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['elemento']);?></td>
	        
	        <td><?php echo $this->escapeHtml($pedido['unidadMedida']);?></td>
	        
	        <td><strong><?php echo $this->escapeHtml($pedido['totalPedido']);?></strong></td>
	        
	    </tr>
	    <?php endforeach; ?>
	    </tbody>
	</table>
	
	<a class="uk-button uk-button-default" href="<?php echo $this->url("reportes", [
																	'action' => 'primer-reporte-pdf',
																	'imprimirpdf' => 'si'
											                     ]); ?>"  target="_blank">Descargar Pdf</a>
	
<?php else: ?>
	
	<h2>No se han encontrado resultados</h2>

<?php endif;?>
</div>