<?php
use Admin\Model\Miscellanea;
?>

<div class="uk-container uk-container-expand uk-padding-small">

	<a class="uk-button uk-button-text" href="<?php echo $this->url('docente', ['action'=> 'ver-cursos']); ?>">Seleccionar otro curso</a>
	|
	<a href="<?php echo $this->url('docente', 
	    ['action'  => 'editar-pedido',
	     'semestre' => $this->semestre,
	     'codescuela' => $this->codEscuela,
	     'codcurso' => $this->curso->codCurso]
	    ); ?>" class="uk-button uk-button-secondary" >Editar requerimiento</a>
	<hr/>
	<div id="print">
    	<p>
    		Semestre: <strong><?= $this->semestre;?></strong> --- 
    		Escuela: <strong><?= $this->escuela->nombreEscuela; ?></strong> ---
    		Curso: <strong><?= $this->curso->nombreCurso; ?></strong>    		
    	</p>
    
    	<?php if($this->requerimientos): ?>	
    	<table class="uk-table uk-table-hover uk-table-striped">
    	    <thead>
    	    <tr>
    	        <th>N°</th>
    	        <th>Tipo</th>
    	        <th>Elemento</th>    	              
    	        <th>Unidad de Medida</th>
    	        <th>Cantidad</th>
    	        <th>Observaciones</th>
    	    </tr>
    	    </thead>
    	    <tbody>
    	    <?php
    	    	$i = 0;
    	    	foreach ($this->requerimientos as $requerimiento) :
    			$i++;
    		?>    
    	    <tr>
    	        <td><?php echo $i;?></td>
    	        
    	        <td><?php echo $this->escapeHtml($requerimiento['tipo']);?></td>
    	        
    	        <td><?php echo $this->escapeHtml($requerimiento['elemento']);?></td>
    	        
    	        <td><?php echo $this->escapeHtml($requerimiento['unidadMedida']);?></td>
    	        
    	        <td><strong><?php echo $this->escapeHtml($requerimiento['cantidad']);?></strong></td>
    	        
    	        <td><?php echo $this->escapeHtml($requerimiento['detalleObservacion']);?></td>
    	    </tr>
    	    <?php endforeach; ?>
    	    </tbody> 
    	</table>    	
	</div>
	
	<a href="<?php echo $this->url('reportes', 
	    ['action'  => 'segundo-reporte-pdf',
         'imprimirpdf' => 'si',
         'codusuario' => $this->codUsuario,
	     'semestre' => $this->semestre,
	     'codescuela' => $this->codEscuela,
	     'codcurso' => $this->curso->codCurso]
	    ); ?>" class="uk-button uk-button-default" target="_blank">Descargar Pdf</a>	
	
	<?php else: ?>
		<h2>Aún no has realizado ningún pedido.</h2>		
	<?php endif;?>
</div>

