
<div class="uk-container uk-container-expand uk-padding-small">

	<p><em>*Recuerde que los pedidos se organizan por semestre y curso.</em></p>

	<?php if($this->cursos->count() != 0): ?>	
	<table class="uk-table uk-table-hover uk-table-striped">
	    <thead>
	    <tr>
	        <th>N°</th>
	        <th>Semestre</th>	        
	        <th><strong>Escuela</strong></th>
	        <th><strong>Curso</strong></th>
	        <th>-</th>
	    </tr>
	    </thead>
	    <tbody>
	    <?php
	    	$i = 0;
	    	foreach ($this->cursos as $curso) :
			$i++;
		?>    
	    <tr>
	        <td><?php echo $i;?></td>
	        
	        <td><?php echo $this->escapeHtml($curso['semestre']);?></td>      
	        
	        <td><strong><?php echo $this->escapeHtml($curso['nombreEscuela']);?></strong></td>	        
	        
	        <td><strong><?php echo $this->escapeHtml($curso['nombreCurso']);?></strong></td>
	        
	        <td>
	        	<a  href="<?php echo $this->url('docente', [
	        	    'action'    => 'ver-pedidos',
                    'semestre'  => $this->escapeHtml($curso['semestre']),
	        	    'codescuela'  => $curso['codEscuela'],
					'codcurso'  => $curso['codCurso']
				]); ?>" class="uk-button uk-button-primary">Ver pedidos</a>
			</td>
	    </tr>
	    <?php endforeach; ?>
	    </tbody> 
	</table>
	
	<?php else: ?>
		<h1>Aún no has realizado ningún pedido.</h1>
		<h3><a class="uk-button uk-button-default" href="<?= $this->url('docente', ['action' => 'nuevo-pedido']) ?>">Click aquí para realizar un nuevo pedido.</a></h3>
	<?php endif;?>
	
</div>
	


